
build: off 

environment:
  JSPM_GITHUB_AUTH_TOKEN:
    secure: 64Ur2veyh/2KC6BjqgVZKlPx5cj5RgZQkw7lyeKBzyJmLb8sucaixeuKrY4psz+7
    
install:
- ps: Install-product node 22
- node --version
- npm install jspm@4.2.0 -g --depth 0
- npm install --depth 0
- jspm config registries.github.auth %JSPM_GITHUB_AUTH_TOKEN%
- jspm install -y
